window:
  dimensions:
    columns: 85
    lines: 16

  padding:
    x: 30
    y: 20

  decorations: full

  startup_mode: Windowed

scrolling:
  history: 10000

  multiplier: 1

font:
  normal:
    family: Source Code Pro

  bold:
    family: Source Code Pro SemiBold

  italic:
    family: Curie

  size: 9

  offset:
    x: 0
    y: 8

  glyph_offset:
    x: 0
    y: 4

  use_thin_strokes: true

draw_bold_text_with_bright_colors: true

colors:
  primary:
    background: '#2E3440'
    foreground: '#D8DEE9'

  normal:
    black:   '#2E3440'
    red:     '#BF616A'
    green:   '#A3BE8C'
    yellow:  '#EBCB8B'
    blue:    '#81A1C1'
    magenta: '#B48EAD'
    cyan:    '#88C0D0'
    white:   '#E5E9F0'

  bright:
    black:   '#4C566A'
    red:     '#BF616A'
    green:   '#A3BE8C'
    yellow:  '#EBCB8B'
    blue:    '#81A1C1'
    magenta: '#B48EAD'
    cyan:    '#8FBCBB'
    white:   '#ECEFF4'

  indexed_colors: []

bell:
  animation: EaseOutExpo
  duration: 1
  color: '0x333333'

background_opacity: 1.0

mouse_bindings:
  - { mouse: Middle, action: PasteSelection }

mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }

  hide_when_typing: true

  url:
    launcher:
     program: open

    modifiers: None

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>"

  save_to_clipboard: false

cursor:
  style: Block

  unfocused_hollow: true

live_config_reload: true

working_directory: None

enable_experimental_conpty_backend: false

alt_send_esc: true

debug:
  render_timer: false

  persistent_logging: false

  log_level: Warn

  print_events: false

  ref_test: false

key_bindings:
- { key: V,        mods: Control|Shift, action: Paste            }
- { key: C,        mods: Control|Shift, action: Copy             }
- { key: Insert,   mods: Shift,         action: PasteSelection   }
- { key: Key0,     mods: Control,       action: ResetFontSize    }
- { key: Equals,   mods: Control,       action: IncreaseFontSize }
- { key: Add,      mods: Control,       action: IncreaseFontSize }
- { key: Subtract, mods: Control,       action: DecreaseFontSize }
- { key: Minus,    mods: Control,       action: DecreaseFontSize }
