window:
  dimensions:
    columns: 85
    lines: 16

  padding:
    x: 0
    y: 0

  decorations: full

  startup_mode: Windowed

scrolling:
  history: 10000

  multiplier: 1

font:
  normal:
    family: Hermit

  bold:
    family: Hermit
    style: Bold

  italic:
    family: Hermit
    style: Italic

  size: 13

  offset:
    x: 0
    y: 0

  glyph_offset:
    x: 0
    y: 0

draw_bold_text_with_bright_colors: true

colors:
  primary:
    background: '#212121'
    foreground: '#eeeeee'

  normal:
    black:   '#212121'
    red:     '#f44336'
    green:   '#4caf50'
    yellow:  '#ffeb3b'
    blue:    '#2196f3'
    magenta: '#e91e63'
    cyan:    '#00bcd4'
    white:   '#eeeeee'

  bright:
    black:   '#616161'
    red:     '#d32f2f'
    green:   '#388e3c'
    yellow:  '#fbc02d'
    blue:    '#1976d2'
    magenta: '#c2185b'
    cyan:    '#0097a7'
    white:   '#9e9e9e'

  indexed_colors: []

bell:
  animation: EaseOutExpo
  duration: 1
  color: '0x333333'

background_opacity: 1.0

mouse_bindings:
  - { mouse: Middle, action: PasteSelection }

mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }

  hide_when_typing: true

  url:
    launcher:
     program: open

    modifiers: None

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>"

  save_to_clipboard: false

cursor:
  style: Block

  unfocused_hollow: true

live_config_reload: true

working_directory: None

enable_experimental_conpty_backend: false

alt_send_esc: true

debug:
  render_timer: false

  persistent_logging: false

  log_level: Warn

  print_events: false

  ref_test: false

key_bindings:
- { key: V,        mods: Control|Shift, action: Paste            }
- { key: C,        mods: Control|Shift, action: Copy             }
- { key: Insert,   mods: Shift,         action: PasteSelection   }
- { key: Key0,     mods: Control,       action: ResetFontSize    }
- { key: Plus,      mods: Control,       action: IncreaseFontSize }
- { key: Minus,    mods: Control,       action: DecreaseFontSize }
