title: Alacritty

class:
  instance: Alacritty
  general: Alacritty

font:
  normal:
    family: Scientifica 
    style: Regular
  bold:
    family: Scientifica 
    style: Bold

  italic:
    family: Scientifica 
    style: Italic

  size: 9.0

window:
  padding:
    x: 7
    y: 7

colors:
  primary:
    background: '#212b30'
    foreground: '#c4c7d1'

  normal:
    black:   '#666666'
    red:     '#f44336'
    green:   '#4caf50'
    yellow:  '#ffeb3b'
    blue:    '#2196f3'
    magenta: '#9c27b0'
    cyan:    '#00bcd4'
    white:   '#fafafa'

  bright:
    black:   '#888888'
    red:     '#e91e63'
    green:   '#8bc34a'
    yellow:  '#f7eb95'
    blue:    '#03a9f4'
    magenta: '#673ab7'
    cyan:    '#0097a7'
    white:   '#e0e0e0'

visual_bell:
  animation: EaseOutExpo
  duration: 0
  color: '#ffffff'

selection:
  save_to_clipboard: true

cursor:
  style: Block

live_config_reload: true 

working_directory: /home/cele

mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }

  url:
    launcher:
      program: xdg-open
      args: []

    modifiers: control

key_bindings:
- { key: V,        mods: Control|Shift, action: Paste            }
- { key: C,        mods: Control|Shift, action: Copy             }
- { key: Insert,   mods: Shift,         action: PasteSelection   }
- { key: Key0,     mods: Control,       action: ResetFontSize    }
- { key: Equals,   mods: Control,       action: IncreaseFontSize }
- { key: Add,      mods: Control,       action: IncreaseFontSize }
- { key: Subtract, mods: Control,       action: DecreaseFontSize }
- { key: Minus,    mods: Control,       action: DecreaseFontSize }
