title: Alacritty

class:
  instance: Alacritty
  general: Alacritty

font:
  normal:
    family: Source Code Pro 
    style: Regular
  bold:
    family: Source Code Pro 
    style: Bold

  italic:
    family: Source Code Pro 
    style: Italic

  size: 7.0

colors:
  primary:
    background: '#1e282d'
    foreground: '#c4c7d1'

  normal:
    black:   '#666666'
    red:     '#eb606b'
    green:   '#c3e88d'
    yellow:  '#f7eb95'
    blue:    '#80cbc4'
    magenta: '#ff2f90'
    cyan:    '#aeddff'
    white:   '#ffffff'

  bright:
    black:   '#ff262b'
    red:     '#eb606b'
    green:   '#c3e88d'
    yellow:  '#f7eb95'
    blue:    '#7dc6bf'
    magenta: '#6c71c4'
    cyan:    '#35434d'
    white:   '#ffffff'

visual_bell:
  animation: EaseOutExpo
  duration: 0
  color: '#ffffff'

selection:
  save_to_clipboard: true

cursor:
  style: Beam

live_config_reload: true 

working_directory: /home/cele

mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }

  url:
    launcher:
      program: xdg-open
      args: []

    modifiers: control

key_bindings:
- { key: V,        mods: Control|Shift, action: Paste            }
- { key: C,        mods: Control|Shift, action: Copy             }
- { key: Insert,   mods: Shift,         action: PasteSelection   }
- { key: Key0,     mods: Control,       action: ResetFontSize    }
- { key: Equals,   mods: Control,       action: IncreaseFontSize }
- { key: Add,      mods: Control,       action: IncreaseFontSize }
- { key: Subtract, mods: Control,       action: DecreaseFontSize }
- { key: Minus,    mods: Control,       action: DecreaseFontSize }
